print("    *")
print("   * *")
print("  *   *")
print(" *     *")
print("***   ***")
print("  *   *")
print("  *   *")
print("  *****")

print("    *","   * *","  *   *"," *     *","***   ***","  *   *","  *   *","  *****", sep="\n")

print("         *")
print("        * *")
print("       *   *")
print("      *     *")
print("     *       *")
print("    *         *")
print("   *           *")
print("  *             *")
print(" *               *")
print("******      *******")
print("     *      *")
print("     *      *")
print("     *      *")
print("     *      *")
print("     ********")

print("    *     "*2)
print("   * *    "*2)
print("  *   *   "*2)
print(" *     *  "*2)
print("***   *** "*2)
print("  *   *   "*2)
print("  *   *   "*2)
print("  *****   "*2)